# Generated by Django 5.1.7 on 2025-04-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
