# Generated by Django 5.1.7 on 2025-04-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_id_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
    ]
